version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "src/"
    schedule:
      interval: "weekly"
    groups:
      dev:
        dependency-type: "development"
      prod:
        dependency-type: "production"
